set(arguments "")
set(expected_code 0)
set(expected_error "")
set(usage "Usage: exchange_info [--version | --help]\n")
if(CASE STREQUAL "version")
    set(arguments --version)
    set(expected_output "deterministic_exchange ${VERSION}\n")
elseif(CASE STREQUAL "help")
    set(arguments --help)
    set(expected_output "${usage}")
elseif(CASE STREQUAL "unknown")
    set(arguments --does-not-exist)
    set(expected_code 2)
    set(expected_output "")
    set(expected_error "${usage}")
elseif(CASE STREQUAL "extra")
    set(arguments --version unexpected)
    set(expected_code 2)
    set(expected_output "")
    set(expected_error "${usage}")
elseif(NOT CASE STREQUAL "default")
    message(FATAL_ERROR "Unknown CLI case: ${CASE}")
endif()

execute_process(COMMAND "${PROGRAM}" ${arguments}
    RESULT_VARIABLE actual_code OUTPUT_VARIABLE actual_output ERROR_VARIABLE actual_error
    TIMEOUT 10)
string(REPLACE "\r\n" "\n" actual_output "${actual_output}")
string(REPLACE "\r\n" "\n" actual_error "${actual_error}")
if(NOT "${actual_code}" STREQUAL "${expected_code}")
    message(FATAL_ERROR "Exit ${actual_code}; expected ${expected_code}. stderr: ${actual_error}")
endif()
if(NOT "${actual_error}" STREQUAL "${expected_error}")
    message(FATAL_ERROR "Unexpected stderr: ${actual_error}")
endif()
if(CASE STREQUAL "default")
    # Phase 2: verify the CLI advertises the now-supported order semantics.
    foreach(required IN ITEMS "deterministic_exchange ${VERSION}" "Milestone: M2 reference matcher"
            "Compiler: " "Configuration: " "Language: C++20" "Matching engine: limit GTC/IOC, market IOC, cancel, replace")
        string(FIND "${actual_output}" "${required}" position)
        if(position EQUAL -1)
            message(FATAL_ERROR "Missing '${required}' in output: ${actual_output}")
        endif()
    endforeach()
elseif(NOT "${actual_output}" STREQUAL "${expected_output}")
    message(FATAL_ERROR "Unexpected stdout: ${actual_output}")
endif()
