file(MAKE_DIRECTORY "${WORK}")
set(output "${WORK}/analysis.csv")
set(arguments --input "${INPUT}" --analysis-csv "${output}")
if(CASE STREQUAL "cadence")
    list(APPEND arguments --observe-every 4)
elseif(CASE STREQUAL "invalid_interval")
    list(APPEND arguments --observe-every 0)
elseif(CASE STREQUAL "missing_output")
    set(arguments --input "${INPUT}" --observe-every 2)
elseif(CASE STREQUAL "same_file")
    configure_file("${INPUT}" "${WORK}/input.txt" COPYONLY)
    set(arguments --input "${WORK}/input.txt" --analysis-csv "${WORK}/input.txt")
elseif(CASE STREQUAL "output_failure")
    set(arguments --input "${INPUT}" --analysis-csv "${WORK}")
elseif(CASE STREQUAL "rejection")
    file(WRITE "${WORK}/rejected.txt" "SCENARIO 1\nNEW 1 1 SELL LIMIT GTC 100 5\nNEW 2 1 BUY LIMIT IOC 100 3\nNEW 1 1 SELL LIMIT GTC 100 2\nEXPECT_REJECT DUPLICATE_ORDER_ID\nNEW 3 1 BUY LIMIT IOC 100 2\n")
    set(arguments --input "${WORK}/rejected.txt" --analysis-csv "${output}" --observe-every 3)
endif()
execute_process(COMMAND "${PROGRAM}" ${arguments} RESULT_VARIABLE status OUTPUT_VARIABLE human ERROR_VARIABLE diagnostic)
if(CASE STREQUAL "invalid_interval" OR CASE STREQUAL "missing_output")
    if(NOT status EQUAL 2)
        message(FATAL_ERROR "Expected usage failure, got ${status}: ${diagnostic}")
    endif()
    return()
elseif(CASE STREQUAL "same_file" OR CASE STREQUAL "output_failure")
    if(NOT status EQUAL 1)
        message(FATAL_ERROR "Expected I/O failure, got ${status}: ${diagnostic}")
    endif()
    if(CASE STREQUAL "same_file")
        file(READ "${INPUT}" before)
        file(READ "${WORK}/input.txt" after)
        if(NOT before STREQUAL after)
            message(FATAL_ERROR "Scenario input was overwritten")
        endif()
    endif()
    return()
endif()
if(NOT status EQUAL 0)
    message(FATAL_ERROR "Analysis failed: ${diagnostic}")
endif()
file(READ "${output}" actual)
file(READ "${EXPECTED}" expected)
string(REPLACE "\r\n" "\n" actual "${actual}")
string(REPLACE "\r\n" "\n" expected "${expected}")
if(CASE STREQUAL "cadence")
    string(REPLACE "\n" ";" lines "${expected}")
    list(GET lines 0 header)
    list(GET lines 4 fourth)
    list(GET lines 6 last)
    set(expected "${header}\n${fourth}\n${last}\n")
elseif(CASE STREQUAL "rejection")
    string(REPLACE "\n" ";" lines "${expected}")
    list(GET lines 0 header)
    set(expected "${header}\n3,1,1,3,100.000000,,100,,,0,2,-1.000000\n4,1,2,5,100.000000,,,,,0,0,\n")
endif()
if(NOT actual STREQUAL expected)
    message(FATAL_ERROR "Unexpected observation CSV:\n${actual}\nExpected:\n${expected}")
endif()
if(NOT human MATCHES "ANALYSIS instrument=1 trades=2")
    message(FATAL_ERROR "Missing human-readable analysis summary: ${human}")
endif()
