execute_process(COMMAND "${PROGRAM}" --csv RESULT_VARIABLE status OUTPUT_VARIABLE actual ERROR_VARIABLE diagnostic)
if(NOT status EQUAL 0)
    message(FATAL_ERROR "Analysis demo failed: ${diagnostic}")
endif()
file(READ "${EXPECTED}" expected)
string(REPLACE "\r\n" "\n" actual "${actual}")
string(REPLACE "\r\n" "\n" expected "${expected}")
if(NOT actual STREQUAL expected)
    message(FATAL_ERROR "Analysis CSV differs from hand-derived fixture. Actual:\n${actual}")
endif()
