if(EXCHANGE_ENABLE_TSAN AND (EXCHANGE_ENABLE_ASAN OR EXCHANGE_ENABLE_UBSAN))
    message(FATAL_ERROR "TSan requires a separate build; disable ASan and UBSan")
endif()

set(EXCHANGE_SANITIZERS "")
if(EXCHANGE_ENABLE_ASAN)
    list(APPEND EXCHANGE_SANITIZERS address)
endif()
if(EXCHANGE_ENABLE_UBSAN)
    list(APPEND EXCHANGE_SANITIZERS undefined)
endif()
if(EXCHANGE_ENABLE_TSAN)
    list(APPEND EXCHANGE_SANITIZERS thread)
endif()

if(EXCHANGE_SANITIZERS)
    if(NOT CMAKE_SYSTEM_NAME STREQUAL "Linux" OR
       NOT CMAKE_CXX_COMPILER_ID MATCHES "^(GNU|Clang)$")
        message(FATAL_ERROR "Project sanitizer profiles require Linux GCC/Clang. Use WSL or Linux CI; native Windows debug/release builds remain available.")
    endif()
    list(JOIN EXCHANGE_SANITIZERS "," EXCHANGE_SANITIZER_NAMES)
    include(CheckCXXSourceCompiles)
    set(CMAKE_REQUIRED_FLAGS "-fsanitize=${EXCHANGE_SANITIZER_NAMES}")
    set(CMAKE_REQUIRED_LINK_OPTIONS "-fsanitize=${EXCHANGE_SANITIZER_NAMES}")
    # A new set of options must trigger a new compile AND link probe.
    unset(EXCHANGE_SANITIZER_LINKS CACHE)
    check_cxx_source_compiles("int main() { return 0; }" EXCHANGE_SANITIZER_LINKS)
    unset(CMAKE_REQUIRED_FLAGS)
    unset(CMAKE_REQUIRED_LINK_OPTIONS)
    if(NOT EXCHANGE_SANITIZER_LINKS)
        message(FATAL_ERROR "Compiler/runtime cannot link requested sanitizers: ${EXCHANGE_SANITIZER_NAMES}")
    endif()
endif()

function(exchange_enable_sanitizers target)
    if(EXCHANGE_SANITIZERS)
        target_compile_options(${target} PRIVATE
            "-fsanitize=${EXCHANGE_SANITIZER_NAMES}" -fno-omit-frame-pointer)
        target_link_options(${target} PRIVATE "-fsanitize=${EXCHANGE_SANITIZER_NAMES}")
        if(EXCHANGE_ENABLE_UBSAN)
            target_compile_options(${target} PRIVATE -fno-sanitize-recover=undefined)
            target_link_options(${target} PRIVATE -fno-sanitize-recover=undefined)
        endif()
    endif()
endfunction()
